experiment:
  id: exp5
  fold: 0
  datapath: ./data/
  train_batch_size: 8
  val_batch_size: 8
  max_epochs: 30
  num_workers: 10
  profiler: false
  scheduler_step: batch
  seed: 42
  device: cuda

model:
  class_name: cloud.models.Unet
  params:
    backbone: resnet50
    checkpoint_path: ./pretrained_models/resnet50.pth

criterion:
  class_name: cloud.loss.BceDiceLoss

optimizer:
  class_name: torch.optim.Adam
  params:
    lr: 0.001

scheduler:
  class_name: torch.optim.lr_scheduler.CosineAnnealingLR
  params:
    T_max: 10
    last_epoch: -1

callbacks:
  - class_name: pytorch_lightning.callbacks.EarlyStopping
    params:
      monitor: 'val_IoU'
      patience: 12
      mode: max
      verbose: True
  - class_name: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: ./assets/exp0/fold_0/checkpoints
      monitor: 'val_IoU'
      mode: max
      save_top_k: 1
      filename: 'best'
      save_weights_only: True

augmentation:
  train:
  - class_name: albumentations.Resize
    params:
      height: 256
      width: 256
      p: 1.0
  - class_name: albumentations.Normalize
    # params:
    #   mean: [0.5, 0.5, 0.5]
    #   std: [0.25, 0.25, 0.25]
    #   max_pixel_value: 1.0
    params:
      mean: [0.3435823, 0.34141567, 0.32860598]
      std: [0.26375622, 0.26217863, 0.2664461]
      max_pixel_value: 1.0
  - class_name: albumentations.pytorch.ToTensorV2
    params:
      transpose_mask: True
  val:
  - class_name: albumentations.Resize
    params:
      height: 256
      width: 256
      always_apply: true
  - class_name: albumentations.Normalize
    # params:
    #   mean: [0.5, 0.5, 0.5]
    #   std: [0.25, 0.25, 0.25]
    #   max_pixel_value: 1.0
    params:
      mean: [0.3435823, 0.34141567, 0.32860598]
      std: [0.26375622, 0.26217863, 0.2664461]
      max_pixel_value: 1.0
  - class_name: albumentations.pytorch.ToTensorV2
    params:
      transpose_mask: True
  test:
  - class_name: albumentations.Resize
    params:
      height: 256
      width: 256
      always_apply: true
  - class_name: albumentations.Normalize
    # params:
    #   mean: [0.5, 0.5, 0.5]
    #   std: [0.25, 0.25, 0.25]
    #   max_pixel_value: 1.0
    params:
      mean: [0.3435823, 0.34141567, 0.32860598]
      std: [0.26375622, 0.26217863, 0.2664461]
      max_pixel_value: 1.0
  - class_name: albumentations.pytorch.ToTensorV2
  # tta:
  # - class_name: cloud.tta.Flip
  #   params:
  #     orientation: horizontal
  # - class_name: cloud.tta.Flip
  #   params:
  #     orientation: vertical
  # - class_name: cloud.tta.Rotate
  #   params:
  #     angles:
  #     - 90.0
  #     - 270.0

metrics:
- class_name: cloud.metrics.IoU
  name: IoU
  params:
    activation: softmax

logger:
  class_name: pytorch_lightning.loggers.WandbLogger
  params:
    project: "cloud"
    # mode: "disabled"
