experiment:
  id: exp110_finetune
  fold: 0
  datapath: ./data/pseudo_labels_3_folds
  train_batch_size: 2
  val_batch_size: 2
  max_epochs: 10
  num_workers: 10
  profiler: false
  scheduler_interval: epoch
  seed: 42
  device: cuda
  ema: False
  pretrained: assets/exp110/fold_0/checkpoints/best.ckpt

model:
  class_name: cloud.models.UnetCRF
  params:
    backbone: timm-resnest50d
    checkpoint_path: ./pretrained_models/resnest50.pth


criterion:
  class_name: cloud.losses.lovasz.LovaszLoss

optimizer:
  class_name: torch.optim.SGD
  params:
    lr: 0.000001
    weight_decay: 0.001

scheduler:
  class_name: torch.optim.lr_scheduler.CosineAnnealingLR
  params:
    T_max: 10
    last_epoch: -1
    eta_min: 0.000001

callbacks:
  - class_name: pytorch_lightning.callbacks.EarlyStopping
    params:
      monitor: 'val_IoU'
      patience: 10
      mode: max
      verbose: True
  - class_name: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: ./assets/exp0/fold_0/checkpoints
      monitor: 'val_IoU'
      mode: max
      save_top_k: 1
      filename: 'best'
      save_weights_only: True
  - class_name: pytorch_lightning.callbacks.LearningRateMonitor
    params:
      logging_interval: epoch

augmentation:
  train:
  # - class_name: albumentations.HorizontalFlip
  #   params:
  #     p: 0.5
  # - class_name: albumentations.VerticalFlip
  #   params:
  #     p: 0.5
  # - class_name: albumentations.RandomRotate90
  #   params:
  #     p: 0.5
  # - class_name: albumentations.Transpose
  #   params:
  #     p: 0.5
  - class_name: albumentations.Normalize
    params:
      mean: [0.34035977429201636, 0.3364873570117102, 0.32115959143162537]
      std: [0.19486441928139522, 0.190782342676511, 0.19202036947511614]
      max_pixel_value: 1.0
  - class_name: albumentations.pytorch.ToTensorV2
    params:
      transpose_mask: True
  val:
  - class_name: albumentations.Normalize
    params:
      mean: [0.34035977429201636, 0.3364873570117102, 0.32115959143162537]
      std: [0.19486441928139522, 0.190782342676511, 0.19202036947511614]
      max_pixel_value: 1.0
  - class_name: albumentations.pytorch.ToTensorV2
    params:
      transpose_mask: True
  test:
  - class_name: albumentations.Normalize
    params:
      mean: [0.34035977429201636, 0.3364873570117102, 0.32115959143162537]
      std: [0.19486441928139522, 0.190782342676511, 0.19202036947511614]
      max_pixel_value: 1.0
  - class_name: albumentations.pytorch.ToTensorV2
  tta:
  - class_name: cloud.tta.Rotate
    params:
      angles:
      - 180.0

metrics:
- class_name: cloud.metrics.IoU
  name: IoU
  params:
    activation: softmax

logger:
  class_name: pytorch_lightning.loggers.WandbLogger
  params:
    project: "cloud"
    # mode: "disabled"